//
//  Constants.h
//  InvHelper
//
//  Created by 谢 祖铭 on 14-3-22.
//  Copyright (c) 2014年 Self. All rights reserved.
//

FOUNDATION_EXPORT const CGSize PHOTO_THUMBNAIL_SIZE;
FOUNDATION_EXPORT const CGSize PHOTO_THUMBNAIL_SIZE_LIST;
FOUNDATION_EXPORT const CGFloat PHOTO_MAX_SIDE_PIEXEL_DEFAULT;
FOUNDATION_EXPORT const CGFloat PHOTO_QUALITY_DEFAULT;
FOUNDATION_EXPORT const unsigned int TIMEOUT_DEFAULT;

FOUNDATION_EXPORT NSString *KEY_SETTINGS;
FOUNDATION_EXPORT const NSString *KEY_TIMEOUT;
FOUNDATION_EXPORT const NSString *KEY_PHOTO_MAX_PIEXEL;
FOUNDATION_EXPORT const NSString *KEY_PHOTO_QUALITY;